### PR TITLE
request 0.3.1 assumes utf-8

### LINKED ISSUE #51: Coding systems errors
I'm getting strange coding systems errors if I try to push notes to anki. I'm using Anki 2.1.14 (7b93e985) and I have downgraded request.el to request 0.3.1, but I get still the error below. I'm pretty sure this not a problem of encoding in the files: I get the errors even if I make a very simple file like this http://ix.io/1PtE. Sometimes as you see I get a failure reason (but I have thee impression not always)...

:ANKI_FAILURE_REASON: Wrong number of arguments: (8 . 8), 10

These default coding systems were tried to encode text
in the buffer ‘ *temp file*’:
  (utf-8-unix (245 . 4194242) (246 . 4194239) (249 . 4194243) (250 .
  4194209) (607 . 4194242) (608 . 4194239) (611 . 4194243) (612 .
  4194217) (961 . 4194243) (962 . 4194221) (1014 . 4194243))
However, each of them encountered characters it couldn’t encode:
  utf-8-unix cannot encode these:           ...
[etc.]

  raw-text no-conversion

### PR DESCRIPTION
**Pull request by dickmao**
The tkf library now defaults to utf-8 encoding (so does not need to be
done in anki-editor).  Further the synchronous bug has been fixed.

Closes #51 #49

### CODE REVIEW

**Comment by rogorido** [comment]
Which is the current status of this issue?

**Comment by louietan** [comment]
Thanks, but the changes to sync mode seems to make Emacs hanging.

**Comment by ejmg** [comment]
@dickmao I appreciate your effort into making this PR to work around this change.

It appears that in the PR, [a snippet of code](https://github.com/louietan/anki-editor/pull/53/files#diff-dcc90f480b3a04362ad7f6845551b41fL154-L162) @louietan wrote to work around callbacks was removed. Could this be why emacs is hanging with this patch?

@dickmao was there a reason you removed this callback?

**Comment by louietan** [comment]
I'm debugging `request.el`, feels like the polling in `request--curl-sync` never ends and blocks the `semaphore` from being signaled.

I put some logs in that function and only get "Accepting process output..." and "Not finished yet, waiting...".
```lisp
(let (finished)
    (prog1 (apply #'request--curl url
                  :semaphore (lambda (&rest _)
                               (request-log 'debug "Semaphore signaled !")
                               (setq finished t))
                  settings)
      (let ((proc (get-buffer-process (request-response--buffer response))))
        (with-local-quit
          (while (not finished)
            (if (request--process-live-p proc)
                (progn
                  (request-log 'debug "Accepting process output...")
                  (accept-process-output proc))
              (request-log 'debug "Not finished yet, waiting...")
              (sleep-for 0 300)))))))
```

**Comment by louietan** [comment]
Substitute `sleep-for` with `sit-for` works now.  I'm gonna find out how they are different.

**Comment by louietan** [comment]
Not really works though, if I make some input events to emacs while it's requesting, it still deadlocks.

**Comment by louietan** [comment]
https://github.com/tkf/emacs-request/issues/132#issue-482189155

**Comment by louietan** [comment]
tkf/emacs-request#132

**Comment by louietan** [comment]
tkf/emacs-request#132

**Comment by leezu** [comment]
@dickmao can you remove the "synchronous bug has been fixed" related changes? Let's first fix the encoding issue. Once the "synchronous bug has been fixed" related changes have been debugged they can be merged in a separate PR. What do you think?

**Comment by dickmao** [comment]
You got it.

**Comment by leezu** [comment]
Thanks! @louietan can the utf-8 fix be merged then?

**Comment by yszhang95** [comment]
Hi, I have an similar issue to #54 . The platform is WINDOWS 11 and the EMCAS version is 28, NT.

Inspired by [comments](https://github.com/louietan/anki-editor/issues/54#issuecomment-787043243) from @moerrari , I revert the [line](https://github.com/louietan/anki-editor/commit/084ffad14fa700ad1ba95d8cbfe4a8f6052e2408#diff-20eb42553ff8c8a9d4bcb2a4c4dd184ff223c43367f688e5a520061a255fd5baL149) back. Now the repository functions. I am not sure if this is an issue or if I should report it here or elsewhere.

Thanks!

**Pull request merged**
