### PR TITLE
added cleaning of latex input for compatibility with cloze cards

### PR DESCRIPTION
**Pull request by WielderOfMjolnir**
#8

### CODE REVIEW

**Comment by louietan** [comment]
H'm, PRs are welcome, and thanks for contributing!

But I'm going to say sorry for not merging this one. Some of the reasons:
- This is not a problem introduced by this package. (See [this](https://apps.ankiweb.net/docs/manual.html#latex-conflicts)).
- The principle of content conversion of this package is that the result should respect the source as much as possible, it shouldn't mess up the result by inserting line breaks or spaces or whatever to it.
- This package doesn't intent to extend or do any hacks to Anki.
- If we decided to deal with this kind of double-brace conflicts for Anki, then we have to sanitize the content for all notes of Cloze, not latex specifically.

**Comment by WielderOfMjolnir** [comment]
Seems completely reasonable to me. I definitively understand that you'd like to respect the source as much as possible.

Would it make sense to add this is an `interactive` method then? As in a way to let the user sanitize they're input before sending it to Anki?

**Comment by louietan** [comment]
After reconsideration, I could accept this idea since this may be indeed useful for users like you who .
Compared to adding interactive args, adding a customization variable would be better IMO, since you don't have to type prefix arg every time submitting.
OK, I'm reopening this PR.

**Comment by WielderOfMjolnir** [comment]
That seems like a good idea!

I implemented it using a custom-variable. I'm thinking it would be preferable if `anki-editor-latex-clean-for-cloze` could also be set to a string, in which case it would assumed to be a white-space separated redefinition of the closing-symbols for the cloze (as mentioned in [the Anki docs](https://apps.ankiweb.net/docs/manual.html#latex-conflicts)). But this would require us to parse for cloze-deletion brackets and make the substitution, which currently is not implemented.

Hence, at the moment, if `anki-editor-latex-clean-for-cloze` is non-nil, successive `}` will be separated by a single space for compatibility with Anki's cloze.

**Comment by louietan** [comment]
Thanks, but a few things have to be addressed before merging
- Since we just clean double braces for all cases, not for cloze specifically, so the name `anki-editor-latex-clean-for-cloze` might not that accurate, what about something like `anki-editor-break-braces-in-latex`?
- `replace-regexp-in-string` does exactly the same as what you do in `anki-editor--clean-latex`, the code below should work

   ```emacs-lisp
   (format "[latex]%s[/latex]" (if anki-editor-latex-clean-for-cloze
                                   (replace-regexp-in-string content "}}" "} } " content)
                                content))
   ```
- After you have made these changes, please squash your commits into one.

**Comment by WielderOfMjolnir** [comment]
- Name change seems like a good idea; done.
- I used `replace-regexp-in-string` first, but it does not handly more than two successive braces, .e.g. `}}}` becomes `} }}` due to `replace-regexp-in-string` making the replacement, and then matching from the index _following_ the replacement. That's why it's important that when making the match we start from the previous matched index, rather than the index following the replacement. Hope that makes sense.
- Tested by hand, which I figured would be sufficient for such a "small" addition. Do you want me to write unit-tests?

**Comment by louietan** [comment]
1. Thanks
2. Did you really have a look at my reply ? There is a trailing space in the replacement. I saw [this](https://github.com/louietan/anki-editor/pull/9/commits/46e145f785d11cefe4dffbf66616b9de4247de95#diff-dcc90f480b3a04362ad7f6845551b41fR504) line of your code, so I thought I could be achieved with `replace-regexp-in-string`
3. Are you serious ? Did you really test it with `{{c1::$\frac{x}{y^{z}}$}}` that's in your issue ?

**Comment by WielderOfMjolnir** [comment]
2. Ah, sorry, I completely missed that! I'll give that go when I get the chance.
3. Yeah, it's not being called for the inlined latex. I tried to see if there was an easy way to add it _after_ processing the latex, but didn't want to make to many changes. I think just adding the same processing code to the inline-wrapper too is the easiest (was meaning to do it earlier but forgot).

I'll have a look tomorrow.

**Comment by louietan** [comment]
This has been added in 647df92aec8149254857b32b24a9bb09ecedbf50.
I'm going to close this to avoid merging conflicts with the refactored code in upstream branch.

**Pull request closed without merging**
